spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: ''
    password: ''
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true